name: liphium_bridge
description: A glue library for cross-platform functionality.
version: 1.0.0

environment:
  sdk: ^3.5.1

dependencies:
  cross_file: ">=0.3.4+2 <1.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
