[package]
  name    = "rust_lib"
  version = "0.1.0"
  edition = "2021"
[lib]
  crate-type = [
    "cdylib",
    "staticlib",
    "lib",
  ]
[dependencies]
  cpal                = { version = "0.15.2" }
  once_cell           = "1.18.0"
flutter_rust_bridge = "=2.0.0-dev.38"
